### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by bermmerb** [twsnmp/TWLogAIAN#1]
the error messege is "no such files or directory"

**Comment by twsnmp** [comment]
What operation did you perform when you saw this error message?
Please attach a screen copy if possible.

**Comment by bermmerb** [comment]
in this step when I start the message appear.

—Berm


￼

**Comment by twsnmp** [comment]
Do you use Windows or Mac OS?
Do you install from the Microsoft Store or the Apple App Store?
Did you launch it from the Start Menu or Launcher?
Or from the command line?

**Comment by bermmerb** [comment]
> Do you use Windows or Mac OS?
> 
MacOS
> Do you install from the Microsoft Store or the Apple App Store?
> 
App store
> Did you launch it from the Start Menu or Launcher?
> 
Launcher
> Or from the command line?
> 
GUI

—Berm

**Comment by twsnmp** [comment]
I just tried to install and test the e-app from the App Store on a Mac mini with an Interl CPU and an M2 CPU, and it started without any problems.

![image](https://github.com/twsnmp/TWLogAIAN/assets/5225950/14417ed3-3331-4aa8-bb70-ad38f8f31648)

**Comment by twsnmp** [comment]
Perhaps the problem occurs in non-Japanese environments.
I will investigate in detail when I have time.

**Comment by twsnmp** [comment]
If you set a folder that does not exist in the working folder selection screen, you will get the same error message.
![image](https://github.com/twsnmp/TWLogAIAN/assets/5225950/21f6aca3-84d4-426f-b481-6f56608b4d6d)

**Comment by bermmerb** [comment]
Thanks, It’s work now.

—Berm

**Comment by twsnmp** [comment]
You're welcome,
I'm glad the app is working.
Close the ticket.
